### PR TITLE
Shield base token

### LINKED ISSUE #36: Notify on transaction send and on success/fail
Build transaction send flow (blocked by #17) and notify

### LINKED ISSUE #40: Use sdk to shield base token
Currently frontend will only shield ERC20s

See [https://docs.railgun.org/developer-guide/quickstart/transactions/shielding/shield-base-token](docs) on how to shield base token

### LINKED ISSUE #49: Create constants.ts and include native ETH address
> Wdyt of having a `constants.ts` file, which defines all frontend constants—supported chains, ETH address, WETH addresses per network, any ABIs, etc? It's a pattern I've used in frontends and find it very helpful. If we do it, it should be a separate issue / PR

_Originally posted by @mds1 in https://github.com/ScopeLift/railgun-shielder/pull/46#discussion_r1081872410_

### PR DESCRIPTION
**Pull request by wildmolasses**
Closes #40 
Closes #49 
Closes #36

- shields base token
- adds weth, consumable from useToken hook
- refactors the shield tx stuff into a hook

### CODE REVIEW

**Review by alexkeating — COMMENTED** [review]
Liking the useRailgunTx hook, noticed one warning that potentially needs resolution

File: hooks/useTokenList.tsx [hunk 1]
```diff
@@ -27,8 +28,18 @@ export const useTokenList = () => {
       const tokenList = json.tokens.filter(
         (token) => token.chainId === chainId
       );
-      return tokenList;
+      const weth = tokenList.find((token) => token.symbol === "WETH")?.address;
+      if (!weth) throw new Error("No WETH found in token list");
```
Comment (mds1) [inline hooks/useTokenList.tsx:32]: Intead of throwing, we can manually define WETH (per-chain, of course, since it's different per-chain). Need to find what the equivalents are for BSC and Polygon, probably WBNB and WMATIC if I had to guess

File: hooks/useRailgunTx.tsx [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+  const { weth } = useToken();
+  const provider = useProvider();
+
+  const shield = async (args: {
+    tokenAddress: string;
+    tokenAmount: string;
+    tokenDecimals: number;
+    recipient: string;
+  }) => {
+    if (args.tokenAddress === getAddress(`0x${"e".repeat(40)}`))
```
Comment (mds1) [inline hooks/useRailgunTx.tsx:37]: Wdyt of having a `constants.ts` file, which defines all frontend constants—supported chains, ETH address, WETH addresses per network, any ABIs, etc? It's a pattern I've used in frontends and find it very helpful. If we do it, it should be a separate issue / PR

File: hooks/useRailgunTx.tsx [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+    // Public wallet to shield from.
+    const fromWalletAddress = address as `0x{string}`;
+
+    // The shieldPrivateKey enables the sender to decrypt
+    // the receiver's address in the future.
+    const shieldPrivateKey = await getShieldPrivateKey();
+
+    const wrappedERC20Amount: RailgunERC20Amount = {
+      tokenAddress: weth!, // wETH
+      amountString: parseUnits(tokenAmount!, tokenDecimals).toHexString(), // hexadecimal amount
```
Comment (mds1) [inline hooks/useRailgunTx.tsx:61]: I think we can remove the `!` assertion from `tokenAmount`. Also is having the amount as a hex string a requirement of the railgun SDK?

File: hooks/useRailgunTx.tsx [hunk 4]
```diff
@@ -0,0 +1,188 @@
...
+    };
+
+    const { gasEstimateString, error: err } =
```
Comment (mds1) [inline hooks/useRailgunTx.tsx:64]: Similarly, does that mean `gasEstimateString` is also a hex string, and not a decimal string? Accepting inputs as ethers.js' `BigNumberish` type and returning `BigNumbers` or `bigint` would be a much nicer SDK interface IMO

File: hooks/useRailgunTx.tsx [hunk 5]
```diff
@@ -0,0 +1,188 @@
...
+    if (err) {
+      throw err;
+    }
+
+    const { maxFeePerGas, maxPriorityFeePerGas } = await provider.getFeeData();
+
+    const gasDetailsSerialized: TransactionGasDetailsSerialized = {
+      evmGasType: EVMGasType.Type2, // Depends on the chain (BNB uses type 0)
+      gasEstimateString: gasEstimateString!, // Output from gasEstimateForShieldBaseToken
+      maxFeePerGasString: maxFeePerGas!.toHexString(), // Current gas Max Fee
```
Comment (mds1) [inline hooks/useRailgunTx.tsx:81]: Do we have an issue tracking all the changes we need when we convert from just Goerli support to supporting all chains? Seems the single-chain assumptions are hardcoded and spread across various locations, worried it may get a bit tedious to refactor. Probably fine though

File: hooks/useRailgunTx.tsx [hunk 6]
```diff
@@ -0,0 +1,188 @@
...
+    if (error) {
+      throw error;
+    }
+
+    const { chain } = NETWORK_CONFIG[network];
+
+    const transactionRequest: ethers.providers.TransactionRequest =
+      deserializeTransaction(
+        serializedTransaction!,
+        undefined, // nonce (optional)
```
Comment (mds1) [inline hooks/useRailgunTx.tsx:101]: Another SDK comment: Having an optional second arg but a required third arg feels a bit clunky. An object with optional fields seems cleaner

File: hooks/useRailgunTx.tsx [hunk 7]
```diff
@@ -0,0 +1,188 @@
...
+        chain.id
+      );
+
+    // Public wallet to shield from.
+    transactionRequest.from = address;
```
Comment (mds1) [inline hooks/useRailgunTx.tsx:106]: Another SDK comment that we discussed—this line should not be necessary, we should just pass this address into `deserializeTransaction` and get the final `transactionRequest` object back. (Leaving these SDK comments here to see if you agree, then we can port them over to our doc)

File: hooks/useRailgunTx.tsx [hunk 8]
```diff
@@ -0,0 +1,188 @@
...
+
+    const transactionRequest: ethers.providers.TransactionRequest =
+      deserializeTransaction(
+        serializedTransaction as string,
+        undefined, // nonce (optional)
+        chain.id
+      );
+
+    // Public wallet to shield from.
+    transactionRequest.from = address;
```
Comment (mds1) [inline hooks/useRailgunTx.tsx:181]: Feels like a lot of duplicate code between the native token and ERC20 methods. Wonder if we can/should dedupe a bit?

File: contexts/TokenContext.tsx [hunk 9]
```diff
@@ -10,17 +10,19 @@ type TokenListContextItem = TokenListItem & { balance: BigNumber | null };
 export type TokenContextType = {
   tokenList: TokenListContextItem[];
   isLoading: boolean;
+  weth?: string;
```
Comment (mds1) [inline contexts/TokenContext.tsx:13]: Personally not a fan of this typing as it's not obvious this `string` should be an address. I'd suggest making the type `TokenInfo` (from the token list, you can get that type from the uniswap token lists package), or renaming these to things like `wethAddress`

File: components/TxForm.tsx [hunk 10]
```diff
@@ -39,13 +22,6 @@ export const TxForm = () => {
...
-  console.log(
-    getRailgunSmartWalletContractForNetwork(NetworkName.EthereumGoerli).address
-  );
-  const { isConnected, address } = useAccount();
-  const { data: signer } = useSigner();
-  const provider = useProvider();
-  const { getShieldPrivateKey } = useShieldPrivateKey();
   const { config } = usePrepareContractWrite({
     address: "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
     abi: erc20ABI,
```
Comment (mds1) [inline components/TxForm.tsx:27]: Above, the `abi` variable is declared but never used

File: components/TxForm.tsx [hunk 11]
```diff
@@ -62,77 +38,20 @@ export const TxForm = () => {
...
-        chain.id
-      );
-
-    // Public wallet to shield from.
-    transactionRequest.from = address;
-    // TODO: handle transaction status and notifications in a feature
-    const tx = await signer?.sendTransaction(transactionRequest);
-    await tx?.wait().then(() => {
-      txNotify(tx.hash);
+    if (!tokenAddress || !tokenAmount || !tokenDecimals || !recipient)
```
Comment (mds1) [inline components/TxForm.tsx:45]: Is checking both `tokenDecimals` and `tokenAddress` redundant? Since they're both populated from the token dropdown

**Review by mds1 — COMMENTED** [review]
UI is working well!

File: hooks/useRailgunTx.tsx (hunk 2 above)
Comment (wildmolasses) [reply hooks/useRailgunTx.tsx:37]: i'm down!

Comment (wildmolasses) [reply hooks/useRailgunTx.tsx:37]: tracking in #49

File: hooks/useRailgunTx.tsx (hunk 3 above)
Comment (wildmolasses) [reply hooks/useRailgunTx.tsx:61]: > Also is having the amount as a hex string a requirement of the railgun SDK?

yes!

File: hooks/useRailgunTx.tsx (hunk 4 above)
Comment (wildmolasses) [reply hooks/useRailgunTx.tsx:64]: good call! currently inputs must be hex strings.

File: hooks/useRailgunTx.tsx (hunk 5 above)
Comment (wildmolasses) [reply hooks/useRailgunTx.tsx:81]: i wrote an issue #48 for the gas type

File: hooks/useRailgunTx.tsx (hunk 8 above)
Comment (wildmolasses) [reply hooks/useRailgunTx.tsx:181]: I looked into deduping, it got a bit convoluted. For simplicity i thought we might PR this version, and if we see the opportunity to refactor then we could go for it. What do you think?

File: components/TxForm.tsx [hunk 12]
```diff
@@ -62,77 +38,20 @@ export const TxForm = () => {
...
+      throw new Error("bad form");
+    const tx = await shield({
+      tokenAddress,
+      tokenAmount,
+      tokenDecimals,
+      recipient,
     });
+    await tx?.wait();
+    txNotify(tx!.hash);
```
[the remark this answers is not in the document]
Comment (wildmolasses) [reply components/TxForm.tsx:53]: handled 14e08c7

File: hooks/useTokenList.tsx (hunk 1 above)
Comment (wildmolasses) [reply hooks/useTokenList.tsx:32]: we could do that, but don't we expect WETH in each token list? and if it's not there, mightn't it be grounds for a big error?

File: hooks/useRailgunTx.tsx (hunk 3 above)
Comment (wildmolasses) [reply hooks/useRailgunTx.tsx:61]: `!` removed c6cccf5

File: hooks/useRailgunTx.tsx (hunk 6 above)
Comment (wildmolasses) [reply hooks/useRailgunTx.tsx:101]: agreed!

File: hooks/useRailgunTx.tsx (hunk 7 above)
Comment (wildmolasses) [reply hooks/useRailgunTx.tsx:106]: yeah feels a lil neater

File: hooks/useTokenList.tsx (hunk 1 above)
Comment (mds1) [reply hooks/useTokenList.tsx:32]: Hmm, yea in theory each token list should have the wrapped version of the native token (WETH), and we can verify that upfront before committing to that token list. Partly related to https://github.com/ScopeLift/railgun-shielder/issues/43, because if the list is a static, local JSON file this line can neve occur. But if loading the token lists from a URL, it's possible the list changes and removes WETH for whatever reason. In that case we _can_ throw an error, but since we know the address of an immutable WETH contract that will always work, we can just plug that in instead

File: contexts/TokenContext.tsx (hunk 9 above)
Comment (wildmolasses) [reply contexts/TokenContext.tsx]: made it a token item 37508e2

File: components/TxForm.tsx (hunk 10 above)
Comment (wildmolasses) [reply components/TxForm.tsx]: fixed!

File: hooks/useRailgunTx.tsx (hunk 2 above)
Comment (wildmolasses) [reply hooks/useRailgunTx.tsx]: update: i just made the constants file in 1836e62

File: hooks/useRailgunTx.tsx (hunk 5 above)
Comment (mds1) [reply hooks/useRailgunTx.tsx:81]: Sounds great, thanks!

File: hooks/useTokenList.tsx [hunk 13]
```diff
@@ -27,8 +28,18 @@ export const useTokenList = () => {
...
+      const eth: TokenListItem = {
+        chainId,
+        symbol: "ETH",
+        address: ethers.utils.getAddress(`0x${"e".repeat(40)}`),
+        decimals: 18,
+        name: "ETH",
+        logoURI: "",
+      };
+      return { tokenList: [eth, ...tokenList], weth };
```
[the remark this answers is not in the document]
Comment (wildmolasses) [reply hooks/useTokenList.tsx:42]: this commit gets balances for eth and includes them in the whole getTokenBalances thing f04d61e

File: components/TxForm.tsx (hunk 11 above)
Comment (wildmolasses) [reply components/TxForm.tsx:49]: perhaps redundant. the alternative is assume the token dropdown is fulfilling its duties.

and typescript won't let me!

Screenshot 2023-01-19 at 11 42 07 PM

File: hooks/useTokenList.tsx (hunk 1 above)
Comment (wildmolasses) [reply hooks/useTokenList.tsx]: ok, how's this for ya! e7051b8

**Review by alexkeating — APPROVED** [review]

File: hooks/useTokenList.tsx (hunk 1 above)
Comment (mds1) [reply hooks/useTokenList.tsx]: Like it! Just needs a few fixes.

First, all the WETH addresses are `0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2` but that's not correct. For example, `cast code 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 --rpc-url $POLYGON_RPC_URL`(or another RPC) shows there is no code at those addresses. Usually you know you've found the right contract because it (1) holds a ton of the native token, and (2) is written in solidity 0.4.18 (or similar) since that's what the original mainnet WETH contract is written in, and everyone copies it

Second, not all of them are called WETH, since WETH = Wrapped Ether and other chains have different native token names, e.g. on matic it's Wrapped Matic / WMATIC

Here's the info you need for each chain, in the format "Name / Symbol / Decimals / Address"
- Mainnet: Wrapped Ether / WETH / 18 / 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
- Goerli: Wrapped Ether / WETH / 18 / 0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6 
- BSC: Wrapped BNB / WBNB / 18 / 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
- Polygon: Wrapped Matic / WMATIC / 18 / 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270
- Arbitrum: Wrapped Ether / WETH / 18 / 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1

File: components/TxForm.tsx (hunk 11 above)
Comment (mds1) [reply components/TxForm.tsx:49]: Ah interesting, I guess you could change that to `tokenDecimals!` instead. Will defer to whichever you prefer, feel free to resolve this comment yourself.

File: hooks/useTokenList.tsx (hunk 1 above)
Comment (wildmolasses) [reply hooks/useTokenList.tsx]: thanks matt will be fixing in #51

Comment (wildmolasses) [reply hooks/useTokenList.tsx]: going to handle in #51 , thank you!
